mod alpha;
mod antiquities;
mod arabian_nights;
mod fallen_empires;
mod legends;
mod the_dark;

use super::record::CardRecord;
use crate::card::{CardBehavior, CardDefinition, CardRules};

static UNSUPPORTED_RULES: CardRules = CardRules::unsupported();

pub(super) fn definitions() -> Vec<CardDefinition> {
    let mut definitions = Vec::with_capacity(128);
    for cards in [
        alpha::CARDS,
        arabian_nights::CARDS,
        antiquities::CARDS,
        legends::CARDS,
        the_dark::CARDS,
        fallen_empires::CARDS,
    ] {
        definitions.extend(cards.iter().map(|record| record.definition()));
    }
    definitions
}

// This is deliberately only an index: every rules value lives with its card.
#[allow(clippy::too_many_lines)]
pub(super) const fn rules(behavior: CardBehavior) -> &'static CardRules {
    match behavior {
        CardBehavior::AnkhOfMishra => &alpha::ANKH_OF_MISHRA.rules,
        CardBehavior::Atog => &antiquities::ATOG.rules,
        CardBehavior::BallLightning => &the_dark::BALL_LIGHTNING.rules,
        CardBehavior::BlackVise => &alpha::BLACK_VISE.rules,
        CardBehavior::BloodMoon => &the_dark::BLOOD_MOON.rules,
        CardBehavior::ChainLightning => &legends::CHAIN_LIGHTNING.rules,
        CardBehavior::CopperTablet => &alpha::COPPER_TABLET.rules,
        CardBehavior::Detonate => &antiquities::DETONATE.rules,
        CardBehavior::Fireball => &alpha::FIREBALL.rules,
        CardBehavior::Fork => &alpha::FORK.rules,
        CardBehavior::GlassesOfUrza => &alpha::GLASSES_OF_URZA.rules,
        CardBehavior::IronStar => &alpha::IRON_STAR.rules,
        CardBehavior::LightningBolt => &alpha::LIGHTNING_BOLT.rules,
        CardBehavior::Mountain => &alpha::MOUNTAIN.rules,
        CardBehavior::RedElementalBlast => &alpha::RED_ELEMENTAL_BLAST.rules,
        CardBehavior::Shatter => &alpha::SHATTER.rules,
        CardBehavior::Smoke => &alpha::SMOKE.rules,
        CardBehavior::StoneGiant => &alpha::STONE_GIANT.rules,
        CardBehavior::SuChi => &antiquities::SU_CHI.rules,
        CardBehavior::WinterOrb => &alpha::WINTER_ORB.rules,
        CardBehavior::BlackLotus => &alpha::BLACK_LOTUS.rules,
        CardBehavior::ChaosOrb => &alpha::CHAOS_ORB.rules,
        CardBehavior::DragonWhelp => &alpha::DRAGON_WHELP.rules,
        CardBehavior::GoblinBalloonBrigade => &alpha::GOBLIN_BALLOON_BRIGADE.rules,
        CardBehavior::GoblinDiggingTeam => &the_dark::GOBLIN_DIGGING_TEAM.rules,
        CardBehavior::GoblinGrenade => &fallen_empires::GOBLIN_GRENADE.rules,
        CardBehavior::GoblinKing => &alpha::GOBLIN_KING.rules,
        CardBehavior::GoblinsOfTheFlarg => &the_dark::GOBLINS_OF_THE_FLARG.rules,
        CardBehavior::GraniteGargoyle => &alpha::GRANITE_GARGOYLE.rules,
        CardBehavior::IronclawOrcs => &alpha::IRONCLAW_ORCS.rules,
        CardBehavior::MishrasFactory => &antiquities::MISHRA_S_FACTORY.rules,
        CardBehavior::MoxEmerald => &alpha::MOX_EMERALD.rules,
        CardBehavior::MoxJet => &alpha::MOX_JET.rules,
        CardBehavior::MoxPearl => &alpha::MOX_PEARL.rules,
        CardBehavior::MoxRuby => &alpha::MOX_RUBY.rules,
        CardBehavior::MoxSapphire => &alpha::MOX_SAPPHIRE.rules,
        CardBehavior::OrcishMechanics => &antiquities::ORCISH_MECHANICS.rules,
        CardBehavior::SolRing => &alpha::SOL_RING.rules,
        CardBehavior::StripMine => &antiquities::STRIP_MINE.rules,
        CardBehavior::WheelOfFortune => &alpha::WHEEL_OF_FORTUNE.rules,
        CardBehavior::Juggernaut => &alpha::JUGGERNAUT.rules,
        CardBehavior::ManaVault => &alpha::MANA_VAULT.rules,
        CardBehavior::Triskelion => &antiquities::TRISKELION.rules,
        CardBehavior::AncestralRecall => &alpha::ANCESTRAL_RECALL.rules,
        CardBehavior::Braingeyser => &alpha::BRAINGEYSER.rules,
        CardBehavior::Counterspell => &alpha::COUNTERSPELL.rules,
        CardBehavior::Disenchant => &alpha::DISENCHANT.rules,
        CardBehavior::FellwarStone => &the_dark::FELLWAR_STONE.rules,
        CardBehavior::Island => &alpha::ISLAND.rules,
        CardBehavior::IvoryTower => &antiquities::IVORY_TOWER.rules,
        CardBehavior::JayemdaeTome => &alpha::JAYEMDAE_TOME.rules,
        CardBehavior::Plains => &alpha::PLAINS.rules,
        CardBehavior::SerraAngel => &alpha::SERRA_ANGEL.rules,
        CardBehavior::SwordsToPlowshares => &alpha::SWORDS_TO_PLOWSHARES.rules,
        CardBehavior::TimeWalk => &alpha::TIME_WALK.rules,
        CardBehavior::Tundra => &alpha::TUNDRA.rules,
        CardBehavior::VolcanicIsland => &alpha::VOLCANIC_ISLAND.rules,
        CardBehavior::Armageddon => &alpha::ARMAGEDDON.rules,
        CardBehavior::Badlands => &alpha::BADLANDS.rules,
        CardBehavior::Balance => &alpha::BALANCE.rules,
        CardBehavior::Bayou => &alpha::BAYOU.rules,
        CardBehavior::BlackKnight => &alpha::BLACK_KNIGHT.rules,
        CardBehavior::BirdsOfParadise => &alpha::BIRDS_OF_PARADISE.rules,
        CardBehavior::BlueElementalBlast => &alpha::BLUE_ELEMENTAL_BLAST.rules,
        CardBehavior::Channel => &alpha::CHANNEL.rules,
        CardBehavior::CityOfBrass => &arabian_nights::CITY_OF_BRASS.rules,
        CardBehavior::Crusade => &alpha::CRUSADE.rules,
        CardBehavior::DarkRitual => &alpha::DARK_RITUAL.rules,
        CardBehavior::DemonicTutor => &alpha::DEMONIC_TUTOR.rules,
        CardBehavior::DivineOffering => &legends::DIVINE_OFFERING.rules,
        CardBehavior::DrainLife => &alpha::DRAIN_LIFE.rules,
        CardBehavior::Earthquake => &alpha::EARTHQUAKE.rules,
        CardBehavior::ErhnamDjinn => &arabian_nights::ERHNAM_DJINN.rules,
        CardBehavior::Forest => &alpha::FOREST.rules,
        CardBehavior::HymnToTourach => &fallen_empires::HYMN_TO_TOURACH.rules,
        CardBehavior::HypnoticSpecter => &alpha::HYPNOTIC_SPECTER.rules,
        CardBehavior::IcatianJavelineers => &fallen_empires::ICATIAN_JAVELINEERS.rules,
        CardBehavior::JuzamDjinn => &arabian_nights::JUZAM_DJINN.rules,
        CardBehavior::LibraryOfAlexandria => &arabian_nights::LIBRARY_OF_ALEXANDRIA.rules,
        CardBehavior::ManaDrain => &legends::MANA_DRAIN.rules,
        CardBehavior::MazeOfIth => &the_dark::MAZE_OF_ITH.rules,
        CardBehavior::MindTwist => &alpha::MIND_TWIST.rules,
        CardBehavior::MishrasWorkshop => &antiquities::MISHRA_S_WORKSHOP.rules,
        CardBehavior::NevinyrralsDisk => &alpha::NEVINYRRALS_DISK.rules,
        CardBehavior::OrderOfLeitbur => &fallen_empires::ORDER_OF_LEITBUR.rules,
        CardBehavior::OrderOfTheEbonHand => &fallen_empires::ORDER_OF_THE_EBON_HAND.rules,
        CardBehavior::Plateau => &alpha::PLATEAU.rules,
        CardBehavior::PsionicBlast => &alpha::PSIONIC_BLAST.rules,
        CardBehavior::Recall => &legends::RECALL.rules,
        CardBehavior::Regrowth => &alpha::REGROWTH.rules,
        CardBehavior::Savannah => &alpha::SAVANNAH.rules,
        CardBehavior::SavannahLions => &alpha::SAVANNAH_LIONS.rules,
        CardBehavior::Scrubland => &alpha::SCRUBLAND.rules,
        CardBehavior::SerendibEfreet => &arabian_nights::SERENDIB_EFREET.rules,
        CardBehavior::SengirVampire => &alpha::SENGIR_VAMPIRE.rules,
        CardBehavior::Sinkhole => &alpha::SINKHOLE.rules,
        CardBehavior::Swamp => &alpha::SWAMP.rules,
        CardBehavior::SylvanLibrary => &legends::SYLVAN_LIBRARY.rules,
        CardBehavior::Taiga => &alpha::TAIGA.rules,
        CardBehavior::Terror => &alpha::TERROR.rules,
        CardBehavior::ThunderSpirit => &legends::THUNDER_SPIRIT.rules,
        CardBehavior::TimeVault => &alpha::TIME_VAULT.rules,
        CardBehavior::Timetwister => &alpha::TIMETWISTER.rules,
        CardBehavior::TropicalIsland => &alpha::TROPICAL_ISLAND.rules,
        CardBehavior::UndergroundSea => &alpha::UNDERGROUND_SEA.rules,
        CardBehavior::WhirlingDervish => &legends::WHIRLING_DERVISH.rules,
        CardBehavior::WhiteKnight => &alpha::WHITE_KNIGHT.rules,
        CardBehavior::ArgothianPixies => &antiquities::ARGOTHIAN_PIXIES.rules,
        CardBehavior::Berserk => &alpha::BERSERK.rules,
        CardBehavior::CityInABottle => &arabian_nights::CITY_IN_A_BOTTLE.rules,
        CardBehavior::CopyArtifact => &alpha::COPY_ARTIFACT.rules,
        CardBehavior::DustToDust => &the_dark::DUST_TO_DUST.rules,
        CardBehavior::EnergyFlux => &legends::ENERGY_FLUX.rules,
        CardBehavior::GiantGrowth => &alpha::GIANT_GROWTH.rules,
        CardBehavior::HurkylsRecall => &antiquities::HURKYLS_RECALL.rules,
        CardBehavior::IcyManipulator => &alpha::ICY_MANIPULATOR.rules,
        CardBehavior::KirdApe => &arabian_nights::KIRD_APE.rules,
        CardBehavior::LlanowarElves => &alpha::LLANOWAR_ELVES.rules,
        CardBehavior::Moat => &legends::MOAT.rules,
        CardBehavior::Pendelhaven => &legends::PENDELHAVEN.rules,
        CardBehavior::RelicBarrier => &legends::RELIC_BARRIER.rules,
        CardBehavior::SageOfLatNam => &antiquities::SAGE_OF_LAT_NAM.rules,
        CardBehavior::SedgeTroll => &legends::SEDGE_TROLL.rules,
        CardBehavior::ScrybSprites => &alpha::SCRYB_SPRITES.rules,
        CardBehavior::StoneRain => &alpha::STONE_RAIN.rules,
        CardBehavior::Tetravus => &antiquities::TETRAVUS.rules,
        CardBehavior::TheAbyss => &legends::THE_ABYSS.rules,
        CardBehavior::WrathOfGod => &alpha::WRATH_OF_GOD.rules,
        CardBehavior::Unsupported => &UNSUPPORTED_RULES,
    }
}
